"""Tracking targets and constants."""
from dataclasses import dataclass

LY_GOVAPI_BASE = "https://ly.govapi.tw/v2"
LY_OFFICIAL_INTERPELLATION = "https://data.ly.gov.tw/odw/ID42Action.action"
GOOGLE_NEWS_RSS = "https://news.google.com/rss/search"

HTTP_TIMEOUT = 30.0
PAGE_LIMIT = 100  # ly.govapi.tw page size


@dataclass(frozen=True)
class Target:
    term: int
    name: str  # 中文姓名


# Full 11th-term list (auto-generated)
TARGETS: list[Target] = [
    Target(term=11, name="吳春城"),
    Target(term=11, name="麥玉珍"),
    Target(term=11, name="林國成"),
    Target(term=11, name="張啓楷"),
    Target(term=11, name="黃珊珊"),
    Target(term=11, name="黃國昌"),
    Target(term=11, name="林憶君"),
    Target(term=11, name="游錫堃"),
    Target(term=11, name="洪申翰"),
    Target(term=11, name="林淑芬"),
    Target(term=11, name="邱鎮軍"),
    Target(term=11, name="陳瑩"),
    Target(term=11, name="黃秀芳"),
    Target(term=11, name="楊曜"),
    Target(term=11, name="廖偉翔"),
    Target(term=11, name="劉建國"),
    Target(term=11, name="蘇清泉"),
    Target(term=11, name="邱慧洳"),
    Target(term=11, name="邱志偉"),
    Target(term=11, name="邱議瑩"),
    Target(term=11, name="張嘉郡"),
    Target(term=11, name="陳亭妃"),
    Target(term=11, name="陳超明"),
    Target(term=11, name="楊瓊瓔"),
    Target(term=11, name="蔡易餘"),
    Target(term=11, name="鄭正鈐"),
    Target(term=11, name="賴瑞隆"),
    Target(term=11, name="謝衣鳯"),
    Target(term=11, name="鍾佳濱"),
    Target(term=11, name="呂玉玲"),
    Target(term=11, name="洪毓祥"),
    Target(term=11, name="丁學忠"),
    Target(term=11, name="陳昭姿"),
    Target(term=11, name="牛煦庭"),
    Target(term=11, name="王世堅"),
    Target(term=11, name="王定宇"),
    Target(term=11, name="王美惠"),
    Target(term=11, name="王鴻薇"),
    Target(term=11, name="伍麗華Saidhai‧Tahovecahe"),
    Target(term=11, name="江啟臣"),
    Target(term=11, name="何欣純"),
    Target(term=11, name="吳沛憶"),
    Target(term=11, name="吳宗憲"),
    Target(term=11, name="吳秉叡"),
    Target(term=11, name="吳思瑤"),
    Target(term=11, name="吳琪銘"),
    Target(term=11, name="李昆澤"),
    Target(term=11, name="李彥秀"),
    Target(term=11, name="李柏毅"),
    Target(term=11, name="林宜瑾"),
    Target(term=11, name="林岱樺"),
    Target(term=11, name="林俊憲"),
    Target(term=11, name="林思銘"),
    Target(term=11, name="林德福"),
    Target(term=11, name="邱若華"),
    Target(term=11, name="柯志恩"),
    Target(term=11, name="柯建銘"),
    Target(term=11, name="徐巧芯"),
    Target(term=11, name="徐欣瑩"),
    Target(term=11, name="徐富癸"),
    Target(term=11, name="馬文君"),
    Target(term=11, name="高金素梅"),
    Target(term=11, name="張宏陸"),
    Target(term=11, name="張智倫"),
    Target(term=11, name="許智傑"),
    Target(term=11, name="郭國文"),
    Target(term=11, name="陳玉珍"),
    Target(term=11, name="陳秀寳"),
    Target(term=11, name="陳俊宇"),
    Target(term=11, name="陳冠廷"),
    Target(term=11, name="陳素月"),
    Target(term=11, name="陳雪生"),
    Target(term=11, name="傅崐萁"),
    Target(term=11, name="游顥"),
    Target(term=11, name="黃仁"),
    Target(term=11, name="黃建賓"),
    Target(term=11, name="黃健豪"),
    Target(term=11, name="黃捷"),
    Target(term=11, name="萬美玲"),
    Target(term=11, name="葉元之"),
    Target(term=11, name="廖先翔"),
    Target(term=11, name="蔡其昌"),
    Target(term=11, name="魯明哲"),
    Target(term=11, name="賴士葆"),
    Target(term=11, name="賴惠員"),
    Target(term=11, name="謝龍介"),
    Target(term=11, name="韓國瑜"),
    Target(term=11, name="顏寬恒"),
    Target(term=11, name="羅廷瑋"),
    Target(term=11, name="羅明才"),
    Target(term=11, name="蘇巧慧"),
    Target(term=11, name="李坤城"),
    Target(term=11, name="王安祥"),
    Target(term=11, name="陳清龍"),
    Target(term=11, name="王育敏"),
    Target(term=11, name="林楚茵"),
    Target(term=11, name="張雅琳"),
    Target(term=11, name="許宇甄"),
    Target(term=11, name="鄭天財Sra Kacaw"),
    Target(term=11, name="王正旭"),
    Target(term=11, name="蔡春綢"),
    Target(term=11, name="翁曉玲"),
    Target(term=11, name="沈伯洋"),
    Target(term=11, name="沈發惠"),
    Target(term=11, name="林月琴"),
    Target(term=11, name="林沛祥"),
    Target(term=11, name="林倩綺"),
    Target(term=11, name="范雲"),
    Target(term=11, name="涂權吉"),
    Target(term=11, name="莊瑞雄"),
    Target(term=11, name="郭昱晴"),
    Target(term=11, name="陳永康"),
    Target(term=11, name="陳培瑜"),
    Target(term=11, name="陳菁徽"),
    Target(term=11, name="葛如鈞"),
    Target(term=11, name="盧縣一"),
    Target(term=11, name="羅美玲"),
    Target(term=11, name="羅智強"),
    Target(term=11, name="洪孟楷"),
    Target(term=11, name="王義川"),
    Target(term=11, name="劉書彬"),
    Target(term=11, name="李貞秀"),
    Target(term=11, name="許忠信"),
]
